### ISSUE TITLE
 autoHide for <fmcSoilMod>

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [DeckerMMIV/FarmSim_Mod_ModsSettings#1]
No effect on the setting autoHide="true" or autoHide="false" in block <fmcSoilMod>. 
What could be the problem?

**Comment by DeckerMMIV** [comment]
That question belongs to the SoilMod mod, and not directly here.

However... SoilMod's `autoHide` argument is only in effect, when the console-command is issued `gsToggleFlightAndNoHUDMode` and the player presses <kbd>O</kbd> to hide/show the game's default info-panels (vehicle-info, weather-/time-info, mini-map, helpbox).

**Comment by Gonimy-Vetrom** [comment]
I got it.
